import { 
  analyzeTextAction, 
  deepCritiqueAction, 
  researchTopicAction, 
  checkUniversityUpdatesAction,
  chatWithTutorAction,
  rewriteTextAction,
  continueWritingAction,
  getSynonymsAction,
  generateChartDataAction,
  parseReferenceAction,
  generateSectionContentAction,
  generateThesisOutlineAction,
  generateGrantProposalAction,
  generateSlidesOutlineAction,
  matchJournalsAction,
  generateLiteratureMatrixAction,
  checkScientificPaperAction,
  generateAnalyticsReportAction,
  generateStudyScheduleAction,
  generateCitationAction,
  runGenericToolAction
} from "@/app/actions";

// This file now acts as a bridge to Server Actions
export const GeminiService = {
  analyzeText: analyzeTextAction,
  deepCritique: deepCritiqueAction,
  researchTopic: researchTopicAction,
  checkUniversityUpdates: checkUniversityUpdatesAction,
  chatWithTutor: chatWithTutorAction,
  rewriteText: rewriteTextAction,
  continueWriting: continueWritingAction,
  getSynonyms: getSynonymsAction,
  generateChartData: generateChartDataAction,
  parseReference: parseReferenceAction,
  generateSectionContent: generateSectionContentAction,
  generateThesisOutline: generateThesisOutlineAction,
  generateGrantProposal: generateGrantProposalAction,
  generateSlidesOutline: generateSlidesOutlineAction,
  matchJournals: matchJournalsAction,
  generateLiteratureMatrix: generateLiteratureMatrixAction,
  checkScientificPaper: checkScientificPaperAction,
  generateAnalyticsReport: generateAnalyticsReportAction,
  generateStudySchedule: generateStudyScheduleAction,
  generateCitation: generateCitationAction,
  runGenericTool: runGenericToolAction
};
